responsive design
crafting-software/crafting-software.github.io pull request #2
Opened 2019-04-02 10:17 UTC by andreeadociu

Responsive design for mobile/ipad

2019-04-04 11:50 UTC, LazarMircea requested changes
Please format the code!

2019-04-04 12:20 UTC, wagner89 commented on _includes/nav.html
> +        <div class="navImg" id="navImg">
Any reason for having the same id for more than one element? It's kind of unorthodox

A bit more on the subject: https://stackoverflow.com/a/9454716

2019-04-04 12:20 UTC, wagner89 commented on _includes/nav.html
> +      <div class="navBar" id="navBar">
Why do elements have the same class and id?

2019-04-04 12:20 UTC, wagner89 commented on _includes/nav.html
> +          <div id="navItems" class="navItems" style="position:absolute; right: 4em; top: 3em; z-index:1;">
Styling should be in CSS files instead of inline where possible, it helps readability (and also, it's good to use styling methods with smaller specificity when possible, so the exceptions can be handled)

2019-04-04 12:20 UTC, wagner89 commented on index.html
> +    <!-- TODO this file has become a mess, refactor it -->
This might be a nice time to do this :)

2019-04-04 12:20 UTC, wagner89 commented on index.html
> +        <span>© 2018 Crafting Software. All rights reserved.</span>
This should be 2019

2019-04-04 12:20 UTC, wagner89 commented on js/main.js
>  // Dean Attali / Beautiful Jekyll 2016
Are these comments some kind of copyright requirement, or can they be deleted?

2019-04-04 12:20 UTC, wagner89 commented on js/main.js
> +   // var element = $("#navLogo")
Please delete commented out code

2019-04-04 12:20 UTC, wagner89 commented on js/main.js
> +      console.log("@@@@@@@@@@@@@@@@@@");
Please make sure there are no unintended `console.log`s in the code

2019-04-05 12:35 UTC, LazarMircea requested changes

2019-04-05 12:35 UTC, LazarMircea commented on css/main.css
> +    right: 0px !important;
try to not use `!important`!  Here for exemple, you can try using the same code but instead of using it on a class try to use it on the ID!

https://uxengineer.com/css-specificity-avoid-important-css/

2019-04-05 12:35 UTC, LazarMircea commented on css/main.css
> +@media only screen and (max-width: 1260px) {
this line can be deleted, you have the same `@media` above.

2019-04-16 11:13 UTC, merged